services:
  relay29:
    build:
      context: .
      target: final
      args:
        - PROJECT=groups.purplekonnektiv.com # OPTIONAL
    depends_on:
      - postgres
    environment:
      - DOMAIN=groups.example.com
      - RELAY_NAME=Groups Relay
      - RELAY_PRIVKEY=XXXXX
      - DATABASE_PATH=postgres://relay29:relay29@postgres/relay29?sslmode=disable
      - PORT=4200
      # OPTIONAL
      - RELAY_DESCRIPTION=Groups Relay
      # - RELAY_CONTACT=contact@example.com
      # - RELAY_ICON=https://example.com/icon.png
    ports:
      - 4200:4200
  postgres:
    image: postgres:17
    environment:
      - POSTGRES_USER=relay29
      - POSTGRES_PASSWORD=relay29
      - POSTGRES_DB=relay29
    volumes:
      - ./db:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin